apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: covid-scrapper
build:
  artifacts:
  - image: covid-scrapper
    context: .
  local:
    push: false
  tagPolicy:
    envTemplate:
       template: "{{.IMAGE_NAME}}:latest"
deploy:
  kubectl:
    manifests:
    - k8s/job.yaml
