apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: covid-scrapper-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: covid-scrapper
            image: covid-scrapper:latest
          restartPolicy: OnFailure